In [1]:
import numpy as np

In [2]:
a = np.arange(11)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[4]

4

In [5]:
a[0:5]

array([0, 1, 2, 3, 4])

In [55]:
a[0:5] = 100

In [56]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
s = a[0:5]

In [59]:
s

array([100, 100, 100, 100, 100])

In [60]:
s[:] =666

In [61]:
s

array([666, 666, 666, 666, 666])

In [62]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [63]:
s

array([666, 666, 666, 666, 666])

In [64]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [65]:
s = a[0:5].copy()

In [66]:
s

array([666, 666, 666, 666, 666])

In [67]:
s[:] = 999

In [68]:
s

array([999, 999, 999, 999, 999])

In [69]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [70]:
mat2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               
               ])

In [71]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
mat2.shape

(3, 3)

In [74]:
mat2[2]

array([7, 8, 9])

In [73]:
mat2[1]

array([4, 5, 6])

In [75]:
mat2[2][2]

9

In [76]:
mat2[2,2]

9

In [77]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
mat2[1:,1:]

array([[5, 6],
       [8, 9]])

In [81]:
mat2[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
mat2[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [32]:
b = np.arange(1,11)

In [33]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
b[b==2]

array([2])

In [37]:
c = np.arange(1,10)

In [38]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
c+c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
c*c

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
c/c

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
1/c

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [43]:
c **4

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [44]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [45]:
np.exp(c)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [46]:
np.max(c)

9

In [47]:
np.min(c)

1

In [48]:
np.log(c)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [49]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
mat2*mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])