Import NumPy as np

In [1]:
import numpy as np

Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [5]:
np.arange(9,51)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(3,3)

array([], dtype=int32)

In [8]:
a = np.arange(9).reshape(3,3)

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a.shape

(3, 3)

Create a 3x3 identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([0.98554386])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [13]:
np.random.randn(25)

array([ 0.28291204, -0.05531277,  0.68394504,  0.50823951,  0.29798297,
        1.36532662,  0.36671838,  0.80625951, -0.6615522 ,  1.79282522,
       -0.15659868, -2.11103354,  0.33181035,  0.65565099,  0.23852967,
       -0.29178736, -0.00232403,  1.20123793, -0.05600997, -2.22849769,
        0.59580042, -1.02569938,  0.44763935,  0.24698802, -0.64962046])

Create the following matrix:

In [28]:
b = np.arange(1,101).reshape(10,10)/10

In [29]:
b

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [17]:
mat = np.arange(1,26).reshape(5,5)

In [18]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
mat[3,4]

20

In [21]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [22]:
mat[4,:]

array([21, 22, 23, 24, 25])

Get the sum of all the values in mat

In [23]:
mat.sum()

325

Get the standard deviation of the values in mat

In [24]:
mat.std()

7.211102550927978

Get the sum of all the columns in mat

In [25]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])