In [1]:
import numpy as np

In [2]:
lst = [1,2,3,45,55]

In [3]:
np.array(lst)

array([ 1,  2,  3, 45, 55])

In [4]:
mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

In [5]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.99099136, 0.96791743, 0.26743724, 0.90593076, 0.6554723 ])

In [16]:
np.random.rand(5,5)

array([[0.02147347, 0.49273457, 0.96931886, 0.68821879, 0.18117748],
       [0.32902858, 0.35252494, 0.69363715, 0.58942533, 0.92731262],
       [0.41114989, 0.00362658, 0.08219078, 0.73716999, 0.58097414],
       [0.45573495, 0.84666619, 0.74380709, 0.44889563, 0.68383185],
       [0.07501145, 0.82061971, 0.35268783, 0.32938497, 0.88528811]])

In [17]:
np.random.randn(6,6)

array([[ 1.21957602, -0.12534292,  0.08300014, -0.92409352, -0.15978494,
        -0.20078406],
       [ 1.05120715, -0.92460543,  0.288334  ,  1.40367691, -0.97564293,
         0.91250212],
       [-1.63733619, -0.37117325,  1.58213152, -0.15894054, -0.58967733,
         0.26957666],
       [-0.92951284,  0.28340154,  0.33439246,  0.16290302,  0.32785204,
        -0.14061682],
       [ 1.12660829,  0.12963815, -0.43286412, -0.29489827, -0.46102416,
        -0.2385404 ],
       [ 0.04198985,  1.18901622,  0.68606435, -1.07974249, -0.32719075,
        -0.77103245]])

In [18]:
np.random.randint(1,6)

3

In [19]:
np.random.randint(1,10,6)

array([8, 8, 9, 7, 6, 6])

In [20]:
np.random.randint(1,50,10)

array([37, 36, 41, 11, 49, 20, 15, 40, 16, 22])

In [21]:
arr = np.arange(25)
r = np.random.randint(0,50,5)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
r

array([30,  7, 22, 40, 27])

In [24]:
arr.shape

(25,)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
r.max()

40

In [27]:
r.min()

7

In [29]:
r.argmax()

3

In [30]:
r.argmin()

1

In [31]:
arr.reshape(25,1).shape

(25, 1)

In [178]:
arr.dtype

dtype('int32')

In [179]:
r.dtype

dtype('int32')

In [185]:
x =[1.0,10.0,100.0]

In [186]:
x = np.array(x)

In [187]:
x.dtype

dtype('float64')