In [52]:
import numpy as np

In [88]:
a = np.arange(11)

In [89]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a[4]

4

In [91]:
a[0:5]

array([0, 1, 2, 3, 4])

In [92]:
a[0:5] = 100

In [107]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [108]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [109]:
s = a[0:5]

In [110]:
s

array([666, 666, 666, 666, 666])

In [111]:
s[:] =666

In [112]:
s

array([666, 666, 666, 666, 666])

In [113]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [114]:
s

array([666, 666, 666, 666, 666])

In [115]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [116]:
s = a[0:5].copy()

In [117]:
s

array([666, 666, 666, 666, 666])

In [118]:
s[:] = 999

In [119]:
s

array([999, 999, 999, 999, 999])

In [120]:
a

array([666, 666, 666, 666, 666,   5,   6,   7,   8,   9,  10])

In [122]:
mat2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               
               ])

In [123]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
mat2.shape

(3, 3)

In [125]:
mat2[1]

array([4, 5, 6])

In [127]:
mat2[2][2]

9

In [128]:
mat2[2,2]

9

In [129]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
mat2[1:,1:]

array([[5, 6],
       [8, 9]])

In [131]:
mat2[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [133]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
mat2[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [136]:
b = np.arange(1,11)

In [137]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
b > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [143]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
b[b==2]

array([2])

In [179]:
c = np.arange(1,10)

In [180]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
c+c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [182]:
c*c

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [183]:
c/c

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [184]:
1/c

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [185]:
c **4

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [186]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [187]:
np.exp(c)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [188]:
np.max(c)

9

In [189]:
np.min(c)

1

In [190]:
np.log(c)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [191]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
mat2*mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])